language: C++
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgsl-dev
            - libopenblas-dev
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgsl-dev
            - libopenblas-dev
    - os: osx
      compiler: clang
script:
  - echo $MATRIX_EVAL
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl openblas zlib ; fi
  - $CXX --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OPENBLAS="$(brew --prefix openblas)" ; fi
  - echo $OPENBLAS
  - make -j 4 CXX=$CXX WITH_OPENBLAS=1 OPENBLAS_LEGACY=1 
  - make OPENBLAS_LEGACY=1 fast-check
