language: C++
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgsl-dev
            - libopenblas-dev
script:
  - echo $MATRIX_EVAL
  - eval "${MATRIX_EVAL}"
  - $CXX --version
  - make -j 4 OPENBLAS_LEGACY=1 
  - make OPENBLAS_LEGACY=1 fast-check
