name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install gfortran libopenblas-dev libgsl-dev zlib1g-dev catch ruby python3 catch2
    - name: make
      run: make debug
    - name: make check
      run: make check
